name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎日22時に実行
    - cron: 0 13 * * *
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.1
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run type check
        run: yarn type-check

      - name: Run test
        run: yarn test
